# -*- coding: utf-8 -*-
"""api.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oCn2EAIFwpp4lhQ_uBPxxq-qZPgZp8Pk
"""

from flask import Flask, request, jsonify
import catboost as cb
import json
import pandas as pd

app = Flask(__name__)

# Load model
model = cb.CatBoostClassifier()
model.load_model("ociss_model.cbm")

# Load category mappings
with open("ociss_categories.json") as f:
    categories = json.load(f)

@app.route("/predict", methods=["POST"])
def predict():
    data = request.json

    df = pd.DataFrame([data])
    probability = model.predict_proba(df)[0][1]

    return jsonify({
        "five_year_survival_probability": round(float(probability), 4)
    })

if __name__ == "__main__":
    app.run()